import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ParsedUrlQuery } from "querystring";

import { wrapper } from "~/redux/store";
import { posts } from "~/redux/features";
import Posts from "~/components/Posts";

interface Page extends ParsedUrlQuery {}

const Home: NextPage = (props: Page) => {
    return (
        <div>
            <Head>
                <title>Next.js / Typescript / React / Redux / ...</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <Image
                src="/jsonplaceholder.png"
                alt="Jsonplaceholder Logo"
                width={184}
                height={148}
            />

            <Posts />
        </div>
    )
}

export const getServerSideProps = wrapper.getServerSideProps(store => async (context) => {
    const { query } = context;
    const { dispatch } = store;

    await dispatch(posts.slice.get());

    return { props: { query } };
});

export default Home;
